// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mhnkdqjeeldnstvkxwpc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1obmtkcWplZWxkbnN0dmt4d3BjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5MTQzODQsImV4cCI6MjA2NjQ5MDM4NH0.9ZrdcalgFY5giJtbXjnm8X2Co8Vjt-wPciUXuNOln3E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);